algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Função :
// Autor :
// Data : 17/04/2019
// Seção de Declarações

var

n,i,total:inteiro
inicio
i<-1
n<-1
para i de 1 ate 10 faca
       para n  de 1 ate 10 faca
              total<-i * n
              escreval(i," x",n," =",total)
       fimpara
       escreval(  )
fimpara

fimalgoritmo
