Algoritmo "vetores"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2019
Var
a:vetor[1..8] de inteiro
b:vetor[1..8] de inteiro
i:inteiro


Inicio
i<-0
para i de 1 ate 8 faca
leia(a[i])
fimpara
para i de 1 ate 8 faca
b[i]<-(a[i]*3)
escreval(b[i])
fimpara


Fimalgoritmo
