algoritmo "pés"
// Função :
// Autor :
// Data : 10/04/2019
// Seção de Declarações 
//exercicio 13
//Elaborar um programa que leia uma medida em pés e apresente o seu valor convertido em metros, lembrando que um pé mede 0.3048 metros.
var
pes,metros:real
inicio
escreva("Digite o valor em pes: ")
leia(pes)
         metros<-pes * 0.3048
         escreval("O valor em metros é", metros)
fimalgoritmo
