algoritmo "semnome"
// Função :
// Autor :
// Data : 13/04/2019
// Crie um programa que lê 4 notas de um aluno, calcula e mostra a //média das notas. 
var
n1,n2,n3,n4,x,nf:real
inicio
escreval("Digite a primeira nota")
leia(n1)
escreval("Digite a segunda nota")
leia(n2)
escreval("Digite a terceira nota")
leia(n3)
escreval("Digite a quarta nota")
leia(n4)
nf<-(n1+n2+n3+n4)/4
escreval("Nota Final:",nf)
fimalgoritmo
