algoritmo "lata"
// Função :
// Autor :
// Data : 10/04/2019
// Seção de Declarações 
//exercicio 17
//Calcular e apresentar o valor do volume de uma lata de óleo, utilizando a fórmula
//VOLUME <- 3.14159 * R 2 * ALTURA.
var
r,altura,vol:real

inicio
escreva("digite o valor do raio: ")
leia(r)
escreva ("digite o valor da altura: ")
leia(altura)
            vol <- 3.141559 * ((r^2) * altura)
            escreval("O valor do volume é:",vol)
fimalgoritmo
