algoritmo "programa volume"
// Função :
// Autor :
// Data : 09/04/2019
// Seção de Declarações
//exercicio 29
//29)Elaborar um programa de computador que calcule e apresente o valor do volume
//de uma esfera. Utilize a fórmula VOLUME &lt;- (4 / 3) * 3.14159 * (RAIO3).
var

v,r:real

inicio
escreval("digite o raio")
leia(r)
v <- (4/3)*3,14159*(r^3)
escreva("informe o valor do volume da esfera: ",v)

fimalgoritmo
