algoritmo "programa soma"
// Função :
// Autor :
// Data : 09/04/2019
// Seção de Declarações
23) Construir um programa que leia três valores numéricos inteiros (representados pelas variáveis A, B e C)
e apresente como resultado final o valor da soma dos quadrados dos três valores lidos.
var

a,b,c,r: inteiro

inicio
escreval("digite o numero")
leia(a)
escreval("digite o numero")
leia(b)
escreval("digite o numero")
leia(c)
r <- (a*a)+(b*b)+(c*c)
escreva("o resultado:",r)
fimalgoritmo
