algoritmo "programa potencia"
// Função :
// Autor :
// Data : 09/04/2019
// Seção de Declarações 
//exercicio 30
//30)Elaborar um programa que leia dois valores numéricos inteiros, os quais
//devem representar a base e o expoente de umapotência, calcule a potência e
//apresente o resultado obtido.
var

a,b,pot,p:real

inicio
escreval("informe a base")
leia(b)
escreval("informe o expoente")
leia(a)
p <- pot(a,b)
escreva("valor da potencia é:",p)
fimalgoritmo
