algoritmo "programa quadrado"
// Função :
// Autor :
// Data : 09/04/2019
// Seção de Declarações
24) Construir um programa que leia três valores numéricos inteiros
(representados pelas variáveis A, B e C) e apresente como
resultado final o valor do quadrado da soma dos três valores lidos.
var

a,b,c,r:real

inicio
escreval("digite o numero")
leia(a)
escreval("digite o numero")
leia(b)
escreval("digite o numero")
leia(c)
r <- (a+b+c)^2
escreva("o soma dos quadrados:",r)
fimalgoritmo
